# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Enter your name', max_length=64, verbose_name='Name')),
                ('company', models.CharField(blank=True, default='', help_text="Enter your Organization's name", max_length=64, verbose_name='Company or Organization')),
                ('email', models.EmailField(default='', error_messages={'invalid': 'Enter a valid email address'}, help_text='Enter your email', max_length=64, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, default='', help_text='Enter your phone number', max_length=32, verbose_name='Phone Number')),
                ('comments', models.TextField(blank=True, default='', help_text='Let us know what is on your mind?')),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this person completed this form')),
                ('was_contacted', models.BooleanField(default=False, help_text='Check this if someone has already reached out to this person', verbose_name='Was contacted or not?')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes relating to contacting this person', verbose_name='Contact Notes')),
                ('referer', models.CharField(blank=True, default='', help_text='This is page the visitor was on before coming on the contact page', max_length=2084, verbose_name='Referring Page')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contacts_contactpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Optional. Title of the widget', max_length=64, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
