# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GistPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gist_gistplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GistPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gist_gistpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('gist_id', models.CharField(default='', help_text='Please supply the GitHub username', max_length=32, verbose_name='Gist ID')),
                ('gist_user', models.CharField(default='', help_text='Please supply the GitHub username', max_length=32, verbose_name='GitHub User')),
                ('file_name', models.CharField(default='', help_text='Optional supply a filename', max_length=64, verbose_name='File Name')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
